all:
	ngrok http -config=ngrok.yml -subdomain=citysim https://localhost:4321
local:
	ngrok http -config=ngrok.yml -subdomain=citysimlocal http://localhost:8080/
vis:
	ngrok http -config=ngrok.yml -subdomain=citysimlocalvis http://localhost:5000/

